version: '3.6'
services:
  ftp:
    build: {context: "."}
    image: corpusops/pure-ftpd
    container_name: pure-ftpd
    privileged: true
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
    - ./local/data:/home/username/
    - ./local/passwd:/etc/pure-ftpd/passwd
    - ./local/ssl:/etc/ssl/private
    - ./rootfs/init.sh:/init.sh
    - ./rootfs/etc/supervisor.d/pureftpd:/etc/supervisor.d/pureftpd
# uncomment for ssl/tls, see https://github.com/corpusops/pureftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
