version: '3.6'
services:
  ftp:
    build: {context: ".", args: {flavor: "${flavor:-latest}"}}
    container_name: pure-ftpd
    privileged: true
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
    - ./local/data:/home/username/
    - ./local/passwd:/etc/pure-ftpd/passwd
    - ./local/ssl:/etc/ssl/private
    - ./rootfs/init.sh:/init.sh
    - ./rootfs/etc/supervisor.d/pureftpd:/etc/supervisor.d/pureftpd
# uncomment for ssl/tls, see https://github.com/corpusops/pureftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
