version: '3.8'
services:
  ftp:
    image: "corpusops/pureftpd:${flavor:-latest}"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./data:/home/username/"
      - "./passwd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/corpusops/pureftpd#tls
      - "./ftpssl:/etc/ssl/private"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
